---
title: "R Notebook"
output: html_notebook
---

```{r, include = FALSE}
library("tidyverse")
library("simts")
library("forecast")
```

# Dados dos Parametros

```{r, message = FALSE, warning = FALSE}
df = read_csv("/workspaces/estatistica.tcc/data/arima_parameters.csv") %>%
    mutate(
        across(everything(), replace_na, 0)
    )
df %>% head()
```

Transformação para long

```{r, message = FALSE, warning = FALSE}
# Primeiro, derreter os dados para um formato longo
df_long <- reshape2::melt(df, id.vars = c("sigma2", "start_date", "end_date"))
# Filtrar os coeficientes AR e MA separadamente
df_ar <- df_long[grep("ar", df_long$variable), ]
df_ma <- df_long[grep("ma", df_long$variable), ]
```

# Gráficos

## Sigma 2

### Distribuição do sigma2

```{r, message = FALSE, warning = FALSE}
df %>% filter(sigma2 != 0.00) %>%
ggplot(aes(x = sigma2, fill = sigma2)) +
  geom_histogram() +
  theme_minimal()
```

### Sigma 2 ao longo do tempo

```{r, message = FALSE, warning = FALSE}
df %>% filter(sigma2 != 0.00) %>%
ggplot(aes(x = start_date, y = sigma2)) +
  geom_point()
```



```{r, message = FALSE, warning = FALSE}
median(df$sigma2)
IQR((df$sigma2))
quantile(df$sigma2, 0.25)
quantile(df$sigma2, 0.75)
```


## Coeficientes AR

### Distribuição do AR

```{r, message = FALSE, warning = FALSE}
df_ar %>% filter(value != 0.00) %>%
ggplot(aes(x = variable, y = value, color = variable)) +
  geom_boxplot() +
  theme_minimal()
```

### AR ao longo do tempo

```{r, message = FALSE, warning = FALSE}
df_ar %>% filter(value != 0.00) %>%
ggplot(aes(x = start_date, y = value, color = variable)) +
  geom_point() +
  facet_wrap(~variable, scales = "free_y") +
  theme_minimal()
```


## Coeficientes MA

### Distribuição do MA

```{r, message = FALSE, warning = FALSE}
df_ma %>% filter(value != 0.00) %>%
ggplot(aes(x = variable, y = value, color = variable)) +
  geom_boxplot() +
  theme_minimal()
```

### AR ao longo do tempo

```{r, message = FALSE, warning = FALSE}
df_ma %>% filter(value != 0.00) %>%
ggplot(aes(x = start_date, y = value, color = variable)) +
  geom_point() +
  facet_wrap(~variable, scales = "free_y") +
  theme_minimal()
```


## Dados Simulados


```{r, warning = FALSE, message = FALSE}
sampled_row <- df %>% sample_n(1)

sampled_row

# Extraindo coeficientes AR e MA
ar_coeffs <- sampled_row %>% dplyr::select(starts_with("ar")) %>% unlist() %>% as.numeric()
ma_coeffs <- sampled_row %>% dplyr::select(starts_with("ma")) %>% unlist() %>% as.numeric()

ar_coeffs
ma_coeffs

# Extraindo sigma2
sigma2_val <- sampled_row$sigma2 %>% as.numeric()
sigma2_val

diff_order <- sampled_row$order %>% as.numeric()
diff_order

# Supondo N = 1000 para o tamanho da série sintética
N <- 1000

sim_data <- gen_arima(N, ar_coeffs, diff_order, ma_coeffs, sigma2_val)
df = sim_data %>% as_tibble()
df = df %>% mutate(t = seq(1, nrow(df)))
df %>% ggplot() + geom_line(aes(x = t, y = V1))
```


```{r}
arima_model <- auto.arima(df$V1)
params = arimaorder(arima_model)
params[1]
params[2]
params[3]
```